<?php

function lego_filter_help($section) {
  if ($section == 'admin/modules#description')
    return t('Allow "part" codes in posts.');
}

function lego_filter_filter_tips($delta, $format, $long = false) {

  if ($long) {
    include_once(drupal_get_path('module', 'lego_filter') .'/lego_filter_help.inc');
    return _lego_filter_tip();
  }
  else {
    $output = t('You can use !Part tags in the text.', array('!Part' =>  l(t('[part]'), "filter/tips/$format", array('fragment' => 'filter-lego_filter-' . $delta))));
    return $output;
  }
}

function lego_filter_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => t('LEGO Filter'));

    case 'description':
      return t('Converts [set] and [part] tags to HTML.');

    case 'process':
      include_once(drupal_get_path('module', 'lego_filter') .'/lego_filter_filter.inc');
      return _lego_filter_process($text, $format);

    case 'settings':
      $form = array();
      $form['lego_filter'] = array(
        '#type' => 'fieldset', 
        '#title' => t('LEGO filter'), 
        '#collapsible' => TRUE, 
        '#collapsed' => FALSE);
      $form['lego_filter']["rebrickable_api_key"] = array(
        '#type' => 'textfield', 
        '#title' => t('Rebrickable API Key'), 
        '#default_value' => variable_get("rebrickable_api_key", ''), 
        '#description' => t('API Key from rebrickable.com, required for data lookups.'));
      $form['lego_filter']["brickset_api_key"] = array(
        '#type' => 'textfield', 
        '#title' => t('Brickset API Key'), 
        '#default_value' => variable_get("brickset_api_key", ''), 
        '#description' => t('API Key from brickset.com, required for data lookups.'));
      return $form;

    default:
      return $text;
  }
}

/**
 * Implements of hook_preprocess_page()
 */
function lego_filter_preprocess_page(&$variables) {
  $module_path = drupal_get_path('module', 'lego_filter');
  drupal_add_css($module_path . '/css/lego_filter.css');
  $variables['styles'] = drupal_get_css();
}
